### ISSUE TITLE
Is there a way to use it with metasploit?

### ISSUE THREAD

**Issue by HackM3nt3** [B4rD4k/Vproxy#1]
I want to know if this tool works with metasploit?

**Comment by rumbis** [comment]
id love to know also that method pumb up

**Comment by B4rD4k** [comment]
Hey guys, actually Vproxy isn't working with metasploit I write to to be standalone Python script.
Please elaborate more if it necessary that vproxy will load as a metasploit module.
10x

**Comment by HackM3nt3** [comment]
buddy, i have to pay several vpns with port forwarding (airvpn is the more popular) when i try to test with several attack vectors, if you make available your tool for metasploit everybody will use it, it will be very popular.

**Comment by B4rD4k** [comment]
I will do a research and decide, thank you for your suggestions.
